### ISSUE TITLE
retinotopy code

### ISSUE THREAD

**Issue by resungod** [vistalab/vistadisp#8]
Hi Vistalab,

I have 2 more questions.
When I set the GUI like below:
![gui](https://cloud.githubusercontent.com/assets/17624055/13893372/ba3c64c2-ed2b-11e5-9a79-18d072f84640.jpg)
I have the below error:
![gui_result](https://cloud.githubusercontent.com/assets/17624055/13893377/c36b79d4-ed2b-11e5-973f-e037e890217c.jpg)

So I did not change any parameters and run the code with the default parameter setting like below:
![gui_default](https://cloud.githubusercontent.com/assets/17624055/13893385/da687f4c-ed2b-11e5-832c-91d5eefcdbd7.jpg)
Then I have the below error:
![gui_default_result](https://cloud.githubusercontent.com/assets/17624055/13893388/e11aa126-ed2b-11e5-9fc4-a8a3c4a95dd9.jpg)

Could you let me know what the problem is?

Thank you so much for your help.

Best,

**Comment by JWinawer** [comment]
It looks like you do not have Psychtoolbox on your Matlab path. You need to
add Psychtoolbox.

-Jon

On Fri, Mar 18, 2016 at 6:07 PM, resungod <notifications@github.com> wrote:

> Hi Vistalab,
>
> I have 2 more questions.
> When I set the GUI like below:
> [image: gui]
> <https://cloud.githubusercontent.com/assets/17624055/13893372/ba3c64c2-ed2b-11e5-9a79-18d072f84640.jpg>
> I have the below error:
> [image: gui_result]
> <https://cloud.githubusercontent.com/assets/17624055/13893377/c36b79d4-ed2b-11e5-973f-e037e890217c.jpg>
>
> So I did not change any parameters and run the code with the default
> parameter setting like below:
> [image: gui_default]
> <https://cloud.githubusercontent.com/assets/17624055/13893385/da687f4c-ed2b-11e5-832c-91d5eefcdbd7.jpg>
> Then I have the below error:
> [image: gui_default_result]
> <https://cloud.githubusercontent.com/assets/17624055/13893388/e11aa126-ed2b-11e5-9fc4-a8a3c4a95dd9.jpg>
>
> Could you let me know what the problem is?
>
> Thank you so much for your help.
>
> Best,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistadisp/issues/8>
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by resungod** [comment]
Hi VistaLab,

Unfortunately, I have to say "No"....Our Matlab path includes Psychtoolbox like below:
![psychtoolbox](https://cloud.githubusercontent.com/assets/17624055/13922949/8a5b6d52-ef4c-11e5-9f5e-4f58f21d5b77.jpg)

Is there any other possibility? 

Thank you so much.

Best,

**Comment by JWinawer** [comment]
It looks like the error you are getting is from this call:

> Screen('screens')

Since 'Screen' is a core Psychtoolbox function, and 'screens' is an
acceptable input argument to the function 'Screen', it looks like you are
having PTB problems. I suggest investigating the basic functionality of PTB
on your system.

Jon

On Mon, Mar 21, 2016 at 11:07 AM, resungod <notifications@github.com> wrote:

> Hi VistaLab,
>
> Unfortunately, I have to say "No"....Our Matlab path includes Psychtoolbox
> like below:
> [image: psychtoolbox]
> <https://cloud.githubusercontent.com/assets/17624055/13922949/8a5b6d52-ef4c-11e5-9f5e-4f58f21d5b77.jpg>
>
> Is there any other possibility?
>
> Thank you so much.
>
> Best,
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistadisp/issues/8#issuecomment-199329646>
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by resungod** [comment]
Hi VistaLab,

Sorry to keep asking questions. However, after updating the Psychtoolbox function, then I have the below error:
![after_update](https://cloud.githubusercontent.com/assets/17624055/13932864/42cb1038-ef78-11e5-84a9-56f9e903a5a1.jpg)

However, when I follow the "'C:\Toolboxes\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\PsychHID.mexw64'", I can see the PsychHID.mexw64.
![psychhid](https://cloud.githubusercontent.com/assets/17624055/13932888/5e8dbe56-ef78-11e5-82ce-1757db67c4f2.jpg)

Could you let me know why I have this error?

I really appreciate your help.

Best,

**Comment by arokem** [comment]
I believe this one is best directed to the Psychtoolbox team: http://psychtoolbox.org/forum/

**Comment by wandell** [comment]
Agreed.  Closing.
